### ISSUE TITLE
on_bars逻辑有漏洞

### ISSUE THREAD

**Issue by pluspku** [vnpy/vnpy_portfoliostrategy#13]
https://github.com/vnpy/vnpy_portfoliostrategy/blob/f6b378c2200b9cb4c5d1996f2c8e35d1b1e4054f/vnpy_portfoliostrategy/utility.py#L40
这边只要收到一个tick在新的一分钟就会on_bars，但是有可能上一分钟其他品种的tick还没有收到。
可能的改进有
1. 检查所有品种都在新的一分钟了才call on_bars
2. 如果延迟时间过长，也call on_bars

**Comment by noranhe** [comment]
PortfolioBarGenerator只是一个示例，遇到的这个问题可以参考一下进阶课程【超越海龟策略精析】的51课时。基本上就是添加了一个绑定的合约，只根据该合约的分钟变化来判断，这样就不会生成多个重复的分钟K线。
