### ISSUE TITLE
组合策略引擎加载较长时间数据且数据存在缺失时会出现空指针异常

### ISSUE THREAD

**Issue by dz8235462** [vnpy/vnpy_portfoliostrategy#16]
StrategyEngine的loar_bar方法，
                if bar:
                    bars[vt_symbol] = bar
                # Otherwise, use previous data to backfill
                elif vt_symbol in bars:
                    old_bar = bars[vt_symbol]
                    
                    bar = BarData(
                        symbol=old_bar.symbol,
                        exchange=old_bar.exchange,
                        datetime=dt,
                        open_price=old_bar.close_price,
                        high_price=old_bar.close_price,
                        low_price=old_bar.close_price,
                        close_price=old_bar.close_price,
                        gateway_name=old_bar.gateway_name
                    )
                    bars[vt_symbol] = bar
以上方法的old_bar = bars[vt_symbol]可能出现为None的情况。建议添加忽略。
                    if old_bar == None:
                        continue
策略模板类实盘监听的k线也存在None的推送，所以此改动不会对已有策略产生影响。

**Comment by noranhe** [comment]
bars本来是个空字典，如果能在bars里找到vt_symbol，说明该合约已经满足过if bar（说明这个bar不是None）的逻辑判断，才能放进bars缓存里

**Comment by dz8235462** [comment]
> bars本来是个空字典，如果能在bars里找到vt_symbol，说明该合约已经满足过if bar（说明这个bar不是None）的逻辑判断，才能放进bars缓存里

从这段代码里本身的确没有问题，我看了一下本地的代码，在这里后面会触发策略的on_bars方法，由于策略内部的需要，我会将一部分bar线置为None，以便于忽略部分不需要计算的合约。所以就导致load_bar里出现了bars里含有none的情况。如果不添加过滤，建议在调用on_bars的时候，传一个bars的拷贝对象，不要直接传入bars对象，容易造成数据的修改

**Comment by noranhe** [comment]
修改load进策略的bar不是共性需求，建议自己进行个性化修改了
