### ISSUE TITLE
engine的load_bar方法传入了对象引用，当策略内部修改bars时，会造成load_bar报错

### ISSUE THREAD

**Issue by dz8235462** [vnpy/vnpy_portfoliostrategy#22]
https://github.com/vnpy/vnpy_portfoliostrategy/issues/16  具体请参考此issue的讨论内容。

主要原因为load_bar会触发on_bars。但传入的bars对象是对象引用，策略内部对bars的所有修改都会影响load_bar。建议改为传入拷贝对象，不影响engine内部逻辑。或添加非空判断

**Comment by noranhe** [comment]
修改load进策略的bar不是共性需求，建议自己进行个性化修改了
